name: Comandos Shell

#Eventos (gatilhos que ativam a execução)
on: [push, pull-request]

jobs:
  rodar-comandos-shell:
    #ambiente
    runs-on: unbuntu-latest
    steps:
        name: Exibir uma string
        run: echo "Olá Mundo!"
        name: Script de várias linhas
        run: |
          node -v
          npm -v

